### ISSUE TITLE
Installer stuck on importing schema

### ISSUE THREAD

**Issue by Bielzinero** [slawkens/myaac#55]
I just extracted the files, put it on my webserver, opened install and it just keeps getting stuck on: Your database is MySQL. Importing schema now...

Any way how to fix this?

**Comment by slawkens** [comment]
Hello,

What version do you try to install?  0.7 or 0.8?

I would suggest looking into apache error log. There will be more informations about this error.

**Comment by Bielzinero** [comment]
I'm using 0.7.10, can't find 0.8

This is my Apache Error Log:

```
[Wed Jun 06 17:28:43.210717 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.211719 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.212218 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.212718 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.213219 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.215220 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.216221 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.216221 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.218722 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.219223 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.219724 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.220223 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.220724 2018] [php7:notice] [pid 13084:tid 1872] [client ::1:55039] PHP Notice:  Undefined index: env in C:\\UniServerZ\\www\\system\\functions.php on line 1040
[Wed Jun 06 17:28:43.232232 2018] [php7:error] [pid 13084:tid 1872] [client ::1:55039] PHP Fatal error:  Uncaught Error: Class 'Cache' not found in C:\\UniServerZ\\www\\system\\libs\\pot\\OTS_DB_MySQL.php:97\nStack trace:\n#0 C:\\UniServerZ\\www\\system\\libs\\pot\\OTS.php(374): OTS_DB_MySQL->__construct(Array)\n#1 C:\\UniServerZ\\www\\system\\database.php(98): POT->connect(Array)\n#2 C:\\UniServerZ\\www\\install\\includes\\database.php(6): require('C:\\\\UniServerZ\\\\w...')\n#3 C:\\UniServerZ\\www\\install\\steps\\5-database.php(52): require('C:\\\\UniServerZ\\\\w...')\n#4 C:\\UniServerZ\\www\\install\\index.php(184): require('C:\\\\UniServerZ\\\\w...')\n#5 {main}\n  thrown in C:\\UniServerZ\\www\\system\\libs\\pot\\OTS_DB_MySQL.php on line 97
```

**Comment by slawkens** [comment]
Ok, this seems to be an error I committed last days - not testing install script before committing.

Should work now.
